version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    container_name: api
    volumes:
      - .:/go/src/app/
    command: >
      sh -c "reflex -s -r '\.go$$' go run main.go"

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simplebank
    ports:
      - '5432:5432'
    container_name: postgres

  postgres-gui:
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://postgres:secret@postgres/simplebank?sslmode=disable
    links:
      - postgres:postgres
    ports:
      - '9232:8080'
    depends_on:
      - postgres
